os: Visual Studio 2015
environment:
  AGE_KEY:
    # public key: age1enkrmannzall06hegqdxevslyfxfqtz87zndnfxf6gnwnenaae5ssty6e3
    secure: Fu4lGhR0X/eRI9oQMHfgQuHsOHXPhWjrIs25BWfqhXV6HPd6oI6fUj3KWQG0DfTiFNUEs+4FHNgFe4C5/8rFlaXr1fESi2YbWJsiBCWpNxg=
install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  # Install janus.
  - curl -sL https://raw.githubusercontent.com/ETCDEVTeam/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  # Install AGE
  - curl -sL https://github.com/FiloSottile/age/releases/download/v1.0.0-beta2/age-v1.0.0-beta2-windows-amd64.zip --output age.zip
  - 7z e age.zip
  - set PATH=./age;%PATH%
  # Set up version from git tags.
  - gitversion.exe > packages/desktop/gitversion.json
  - ps: $env:VERSION_BASE = "v$(gitversion.exe /showvariable Major).$(gitversion.exe /showvariable Minor).x"
  # expected by Electron Builder config
  - ps: $env:APP_VERSION_GIT_TAG="$(gitversion.exe /showvariable FullSemVer)-$(gitversion.exe /showvariable ShortSha)"
  - echo %VERSION_BASE% %APP_VERSION_GIT_TAG%
  # Set up build dependencies.
  - ps: Install-Product node 8 x64
  - set CI=true
  - npm install -g npm windows-build-tools@4.0.0 node-gyp lerna yarn@1.13.0
  - ps: $env:Path += ";$env:USERPROFILE\.windows-build-tools\python27"
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set python %USERPROFILE%\.windows-build-tools\python27\python.exe
  # Download dependencies
  - lerna bootstrap

build: off
version: '{build}'
test_script:
  # CSC...=false env var disables app signing for osx, can't hurt to have it here too.
  # But probably useless, since the dist script build for _current_ operating system.
  - yarn build:dist
artifacts:
  - path: './packages/desktop/dist/*.exe'
    name: emerald-wallet
deploy_script:
  - echo %AGE_KEY% > age.txt
  - age -d -i age.txt ./gcloud.age > gcloud.json
  - ps: >-
      If (($env:APPVEYOR_REPO_BRANCH -eq 'master') -or ($env:APPVEYOR_REPO_TAG -eq 'true')) {
          echo "Deploy to http://builds.etcdevteam.com/emerald-wallet/$env:VERSION_BASE/"
          janus.exe deploy -to="builds.etcdevteam.com/emerald-wallet/$env:VERSION_BASE/" -files="./packages/desktop/dist/*.exe" -key="./gcloud.json"
      }
  - rm gcloud.json
  - rm age.txt
