os: Previous Visual Studio 2015
environment:
  GCP_PASSWD:
    secure: erzLJz7qT0kCJa+jZG6Sf9wwkfLYO2UDLzydkKTdwqA=
install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  # Install janus.
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  # Set env var for electron builder version
  - ps: $env:APP_VERSION_GIT_TAG = "$(janus.exe version -format TAG_OR_NIGHTLY)"
  - echo %APP_VERSION_GIT_TAG%

  # Set up build dependencies.
  - ps: Install-Product node 6 x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - bash ./dependencies.sh
build: off
version: '{build}'
test_script:
  - npm run dist
artifacts:
  - path: './dist/*.exe'
    name: emerald-wallet
deploy_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
          janus.exe deploy -to="builds.etcdevteam.com/emerald-wallet/$(janus version -format='v%M.%m.x')/" -files="./dist/*.exe" -key="./gcloud-appveyor.json.enc"
      }
